replicaCount: 1
image:
  php:
    Repository: registry.cn-shanghai.aliyuncs.com/demo-sh/php # {"$imagepolicy": "guoshaobo:php:name"}
    tag: 7.3.321 # {"$imagepolicy": "guoshaobo:php:tag"}
  nginx:
    Repository: registry.cn-shanghai.aliyuncs.com/demo-sh/nginx # {"$imagepolicy": "guoshaobo:nginx:name"}
    tag: 1.25.21 # {"$imagepolicy": "guoshaobo:nginx:tag"}
  pullPolicy: IfNotPresent
imagePullSecrets: "regcred"
podLabels:
  app: "phpinfo-demo"
containerPort: 80
volumeMount:
  phpInfoPhp:
    name: phpinfo-php
    mountPath: /var/www
  wwwConf:
    name: www-conf
    mountPath: /etc/opt/remi/php73/php-fpm.d
  phpInfoConf:
    name: phpinfo-conf
    mountPath: /etc/nginx/conf.d
service:
  type: ClusterIP
  port: 80
ingress:
  phpInfoDemo:
    host: "phpinfo-demo"
    path: "/"
    port: 80
