apiVersion: v1
kind: ConfigMap
metadata:
    name: phpinfo-conf
data:
  phpinfo.conf: |
    server {
        listen       80;
        server_name  localhost phpinfo.demo;
        root   /var/www/;
        access_log /var/log/nginx/access; 
        error_log  /var/log/nginx/error error;
        location / {
            index  index.html index.htm index.php phpinfo.php;
        }
        location ~ [^/]\.php(/|$) {
            fastcgi_pass unix:/dev/shm/php-fpm.sock;
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
            fastcgi_param  PATH_INFO        $fastcgi_path_info;
        }
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
    name: phpinfo-php
data:
  phpinfo.php: |
    <?php
     phpinfo();
    ?>


---
apiVersion: v1
kind: ConfigMap
metadata:
    name: www-conf
data:
  www.conf: |
    [www]
    user = root 
    group = root
    listen = /dev/shm/php-fpm.sock;
    listen.mode = 0666
    pm = dynamic
    pm.max_children = 50
    pm.start_servers = 5
    pm.min_spare_servers = 5
    pm.max_spare_servers = 35
    slowlog = /var/opt/remi/php73/log/php-fpm/www-slow.log
    php_admin_value[error_log] = /var/opt/remi/php73/log/php-fpm/www-error.log
    php_admin_flag[log_errors] = on
    php_value[session.save_handler] = files
    php_value[session.save_path]    = /var/opt/remi/php73/lib/php/session
    php_value[soap.wsdl_cache_dir]  = /var/opt/remi/php73/lib/php/wsdlcache

