apiVersion: v1
kind: Service
metadata:
  name: {{ include "phpinfo-demo.fullname" . }}
spec:
  selector:
    app: {{ include "phpinfo-demo.fullname" . }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
