---
apiVersion: v1
kind: Secret
metadata:
  name: phpinfo-demo
  namespace: guoshaobo
stringData:
  identity: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAAAMwAAAAtzc2gtZW
    QyNTUxOQAAACAbPaNxpiw2VoC0cTjpm2a/3zg1Ye/k+hkgRi2ANMxcIwAAAJBqpB+SaqQf
    kgAAAAtzc2gtZWQyNTUxOQAAACAbPaNxpiw2VoC0cTjpm2a/3zg1Ye/k+hkgRi2ANMxcIw
    AAAED3FhLqIU/Rrn4AO2c8F9w1odlvbAw9UTv0fRwDnWb+9Rs9o3GmLDZWgLRxOOmbZr/f
    ODVh7+T6GSBGLYA0zFwjAAAACWd1b3NoYW9ibwECAwQ=
    -----END OPENSSH PRIVATE KEY-----
  identity.pub: |
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBs9o3GmLDZWgLRxOOmbZr/fODVh7+T6GSBGLYA0zFwj
  known_hosts: '[47.101.174.187]:10022 ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBN3d/BWxeijCZOix5Q7Kqka2W4zl8JddXtEJcpPHqjWgTD5+7DBIsAS7vI5u6ny+cL5+5vBe8MdCe3KOF6FjHTo='

